### ISSUE TITLE
Failed to connect to seed broker

### ISSUE THREAD

**Issue by zaimanza** [tomasAlabes/graphql-kafkajs-subscriptions#13]
I've followed the codumentations on README and got this error
`{"level":"ERROR","timestamp":"2021-10-21T09:27:19.691Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 127.0.0.1:9092","broker":"localhost:9092","clientId":"my-client","stack":"Error: connect ECONNREFUSED 127.0.0.1:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"}
[0] {"level":"ERROR","timestamp":"2021-10-21T09:27:19.693Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 127.0.0.1:9092","retryCount":0,"retryTime":10}
[0] {"level":"ERROR","timestamp":"2021-10-21T09:27:19.709Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 127.0.0.1:9092","broker":"localhost:9092","clientId":"my-client","stack":"Error: connect ECONNREFUSED 127.0.0.1:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"}`

Here is my code:
`const pubsub = KafkaPubSub.create({
    topic: 'my-topic',
    kafka: new Kafka({
        clientId: 'my-topic',
        ssl: true,
        brokers: ['localhost:9092'],
        retry: {
            initialRetryTime: 10,
            retries: 10,
            maxRetryTime: 10,
        },
    }),
    groupIdPrefix: "my-group-id-prefix", // used for kafka pub/sub,
    producerConfig: {}, // optional kafkajs producer configuration
    consumerConfig: {} // optional kafkajs consumer configuration
});`

Is there a way to fix this?

**Comment by tomasAlabes** [comment]
Closing as this is a local problem with the connection to kafka.
